services:
  postgres_db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password1234
      POSTGRES_DB: EcommerceDB
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./product.sql:/docker-entrypoint-initdb.d/product.sql
    networks:
      - ecommerce-network

  backend:
    build: ./backend
    restart: always
    depends_on:
      - postgres_db
    ports:
      - "3000:3000"
    networks:
      - ecommerce-network

  frontend:
    build: ./frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "5173:5173"
    networks:
      - ecommerce-network

volumes:
  postgres-data:

networks:
  ecommerce-network:
    driver: bridge